# Generated by Django 2.2.2 on 2021-05-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('doc', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('address_street', models.CharField(max_length=60)),
                ('address_number', models.IntegerField()),
                ('address_zip_code', models.IntegerField()),
                ('address_city', models.CharField(max_length=60)),
            ],
        ),
    ]
