# Generated by Django 2.2.2 on 2021-05-21 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('component_1_multiply_by', models.CharField(choices=[('AL', 'Alto'), ('AN', 'Ancho'), ('PE', 'Perímetro'), ('NA', 'Nada')], max_length=2)),
                ('component_1_factor', models.DecimalField(decimal_places=2, default='NA', max_digits=50)),
                ('component_1_tolerance', models.DecimalField(decimal_places=2, default='NA', max_digits=50)),
                ('component_2_multiply_by', models.CharField(choices=[('AL', 'Alto'), ('AN', 'Ancho'), ('PE', 'Perímetro'), ('NA', 'Nada')], max_length=2)),
                ('component_2_factor', models.DecimalField(decimal_places=2, default='NA', max_digits=50)),
                ('component_2_tolerance', models.DecimalField(decimal_places=2, default='NA', max_digits=50)),
                ('component_3_multiply_by', models.CharField(choices=[('AL', 'Alto'), ('AN', 'Ancho'), ('PE', 'Perímetro'), ('NA', 'Nada')], max_length=2)),
                ('component_3_factor', models.DecimalField(decimal_places=2, default='NA', max_digits=50)),
                ('component_3_tolerance', models.DecimalField(decimal_places=2, default='NA', max_digits=50)),
                ('component_making_multiply_by', models.CharField(choices=[('AL', 'Alto'), ('AN', 'Ancho'), ('PE', 'Perímetro'), ('NA', 'Nada')], max_length=2)),
                ('component_making_factor', models.DecimalField(decimal_places=2, default='NA', max_digits=50)),
                ('component_making_tolerance', models.DecimalField(decimal_places=2, default='NA', max_digits=50)),
                ('component_1_raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_raw_material_comp_1', to='costs.Cost', verbose_name='Materia prima componente 1')),
                ('component_2_raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_raw_material_comp_2', to='costs.Cost', verbose_name='Materia prima componente 2')),
                ('component_3_raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_raw_material_comp_3', to='costs.Cost', verbose_name='Materia prima componente 3')),
                ('component_making_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_comp_making_cost', to='costs.Cost', verbose_name='Costo confección')),
            ],
        ),
    ]
