# Generated by Django 2.2.2 on 2021-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='factor_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, verbose_name='Factor componente 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='factor_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, verbose_name='Factor componente 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='factor_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, verbose_name='Factor componente 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='making_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, verbose_name='Factor costo confección'),
        ),
        migrations.AlterField(
            model_name='product',
            name='making_multiplier',
            field=models.CharField(choices=[('H', 'Alto'), ('W', 'Ancho'), ('P', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2, verbose_name='Factor medidad multiplicadora costo confección'),
        ),
        migrations.AlterField(
            model_name='product',
            name='making_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, verbose_name='Tolerancia costo confección'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplier_1',
            field=models.CharField(choices=[('H', 'Alto'), ('W', 'Ancho'), ('P', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2, verbose_name='Factor medidad multiplicadora componente 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplier_2',
            field=models.CharField(choices=[('H', 'Alto'), ('W', 'Ancho'), ('P', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2, verbose_name='Factor medidad multiplicadora componente 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplier_3',
            field=models.CharField(choices=[('H', 'Alto'), ('W', 'Ancho'), ('P', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2, verbose_name='Factor medidad multiplicadora componente 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tolerance_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, verbose_name='Tolerancia componente 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tolerance_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, verbose_name='Tolerancia componente 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tolerance_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, verbose_name='Tolerancia componente 3'),
        ),
    ]
