# Generated by Django 2.2.2 on 2021-05-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210528_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='making_multiplier',
            field=models.CharField(choices=[('H', 'Alto'), ('W', 'Ancho'), ('P', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2, verbose_name='Factor medida multiplicadora costo confección'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplier_1',
            field=models.CharField(choices=[('H', 'Alto'), ('W', 'Ancho'), ('P', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2, verbose_name='Factor medida multiplicadora componente 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplier_2',
            field=models.CharField(choices=[('H', 'Alto'), ('W', 'Ancho'), ('P', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2, verbose_name='Factor medida multiplicadora componente 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplier_3',
            field=models.CharField(choices=[('H', 'Alto'), ('W', 'Ancho'), ('P', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2, verbose_name='Factor medida multiplicadora componente 3'),
        ),
    ]
