# Generated by Django 2.2.2 on 2021-05-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='category',
        ),
    ]
