# Generated by Django 2.2.2 on 2021-05-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.CharField(choices=[('CO', 'Confección'), ('MP', 'Materia prima')], max_length=2),
        ),
    ]
