# Generated by Django 2.2.2 on 2021-05-29 16:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Largo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho'),
        ),
    ]
