# Generated by Django 2.2.2 on 2021-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210522_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('NE', 'Nuevo'), ('ER', 'Esperando respuesta'), ('AC', 'Aceptado'), ('MK', 'En confección'), ('FI', 'Terminado')], default='ER', max_length=1),
        ),
    ]
