# Generated by Django 2.2.2 on 2021-05-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210524_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_first_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_tel',
            field=models.CharField(default=None, max_length=50, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabric',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='orders.Order'),
        ),
    ]
