# Generated by Django 2.2.2 on 2021-06-01 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210531_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='orders.Order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='price_per_size',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Precio por metro'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Metros (cantidad)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=None, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.Order', verbose_name='Pedido'),
        ),
    ]
