# Generated by Django 2.2.2 on 2021-06-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210531_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CA', 'Tarjeta'), ('EF', 'Efectivo'), ('CH', 'Cheque'), ('DE', 'Depósito'), ('MP', 'MercadoPago'), ('TR', 'Transferencia Bancaria')], default='EF', max_length=2, verbose_name='Medio de pago'),
        ),
    ]
