# Generated by Django 2.2.2 on 2021-06-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('CH', 'Cheque'), ('DE', 'Depósito'), ('MP', 'MercadoPago'), ('CA', 'Tarjeta'), ('TR', 'Transferencia Bancaria')], default='EF', max_length=2, verbose_name='Medio de pago'),
        ),
    ]
