# Generated by Django 2.2.2 on 2021-05-25 21:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210525_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='component_1_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='component_1_multiply_by',
            field=models.CharField(choices=[('AL', 'Alto'), ('AN', 'Ancho'), ('PE', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='component_1_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='component_2_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='component_2_multiply_by',
            field=models.CharField(choices=[('AL', 'Alto'), ('AN', 'Ancho'), ('PE', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='component_2_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='component_3_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='component_3_multiply_by',
            field=models.CharField(choices=[('AL', 'Alto'), ('AN', 'Ancho'), ('PE', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='component_3_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='making_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='making_multiply_by',
            field=models.CharField(choices=[('AL', 'Alto'), ('AN', 'Ancho'), ('PE', 'Perímetro'), ('NA', 'Nada')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='making_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
