# Generated by Django 2.2.2 on 2021-06-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210615_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_zip_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Código Postal'),
        ),
    ]
